import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15

[window]
option_as_alt = "Both"
decorations = "Buttonless"

