import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 15

[window]
option_as_alt = "Both"
startup_mode = "Maximized"
decorations = "Buttonless"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
